### ISSUE TITLE
make js

### ISSUE THREAD

**Issue by aplikatika** [aplikatika/Espruino-on-ESP8266#2]
I added an option 'js' for flashing ./js/main.js file to 0x60000 but due to my lack of knowledge on makefile I failed. It doesnt flash but outputs: 'js' is up to date.

**Comment by samehhady** [comment]
fixed it for you
https://github.com/samehhady/Espruino-on-ESP8266/blob/master/Makefile

I had to change the path and the name of the make, instead of calling it js I called it jsfile because there is a folder on root called js too so it was conflicting.

**Comment by samehhady** [comment]
I've tried to flash the new bins + flash the js and now I get looots of 1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

not sure why is that.

**Comment by samehhady** [comment]
and at the end I read:
error reading flash
Main:

console.log('It works!');
ààààààààààààààààààààààààààààààà

undefined

Execution Interrupted.

**Comment by samehhady** [comment]
at least it reads the console.log part from the js file :D

**Comment by aplikatika** [comment]
Thank you Sameh for fixing makefile! I will update my version in no time...

It is strange that your device behaves different than mine, but I think the reason is because of very different environment (OS, Xtensa, SDK and ESP), we need to determine that. Also different size of binaries.

In your case flash reading error occures (I suppose) because you have different characters in empty flash area than me, there is no real EOF in the end of uploaded JS file... But let me investigate it now...

**Comment by samehhady** [comment]
I guess you are right, I guess we have to add empty bin file in 0x60000 first to make sure it is empty.

Do you think we will be able to use the Espruino api instead? they have save, update functions and they have Chrome extension which lets you upload sketch.
